### ISSUE TITLE
unable to update/save existing test case

### ISSUE THREAD

**Issue by ppeou** [jsperf/jsperf.com#403] opened 2017-06-23 03:30 UTC
Hello,

I am having issue trying to update my test case.

https://jsperf.com/p-vs-input-1

**Comment by HolgerJeromin** [comment] 2017-06-23 08:10
duplicate of #236

**Closed** 2017-06-23 08:23 UTC

**Comment by ppeou** [comment] 2017-06-23 13:31
Hi Mathiasbynens, any update on this bug? Is it still open?
