### ISSUE TITLE
Saves revision without snippets

### ISSUE THREAD

**Issue by urrri** [jsperf/jsperf.com#330] opened 2017-01-30 12:45 UTC
I switch to editing test, made some changes (or not) and press save. It notifies about error "Not all tests saved", stays in edit page and creates public revision without snippets in background. 
Please fix it, because it is useless with this problem.
Browser Chrome 55

**Comment by maxbeatty** [comment] 2017-01-30 16:50
Duplicate of #236

**Closed by maxbeatty** 2017-01-30 16:50 UTC
