### ISSUE TITLE
Blocked every time by cloudflare with jQuery

### ISSUE THREAD

**Issue by neopheus** [jsperf/jsperf.com#520] opened 2020-01-04 19:08 UTC
Hello everyone :)

jsperf is a great tool :)
but i have a problem to create some new benchmarks

Indeed, if I add a tag like this (in preparation code):

`<script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>`

or 

`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>`

I have an error from Cloudflare : 

> Sorry, you have been blocked
You are unable to access jsperf.com

Thx

**Comment by asilluron** [comment] 2020-01-05 19:12
duplicate of #518

Continuing the discussion there.

**Closed by asilluron** 2020-01-05 19:12 UTC
Labels: duplicate
