### ISSUE TITLE
Unable to save updated test

### ISSUE THREAD

**Issue by xvash** [jsperf/jsperf.com#275] opened 2016-11-22 19:32 UTC
Save test case gives "Please review required fields and save again." after adding/modifying tests.

Even if I change any of the required fields, I get the same message.

![jsperf-bug](https://cloud.githubusercontent.com/assets/2887652/20538652/fd803ddc-b0a6-11e6-9030-052d4bba14cb.png)

**Comment by phistuck** [comment] 2016-11-25 21:57
Me, too.
https://jsperf.com/membernullchecks/1/edit
https://jsperf.com/member-null-checks/1/edit
:(

**Comment by kof** [comment] 2016-11-27 09:24
Confirm that. Was trying to save like crazy.

**Comment by demoneaux** [comment] 2016-11-27 09:45
Duplicate of #236.

**Comment by mathiasbynens** [comment] 2016-11-27 15:10
Closing as duplicate of #236.

**Closed by mathiasbynens** 2016-11-27 15:10 UTC
