### ISSUE TITLE
Some tests are not getting posted properly

### ISSUE THREAD

**Issue by mathiasbynens** [jsperf/jsperf.com#236] opened 2016-10-19 07:29 UTC
The `<table>` on https://jsperf.com/cash-vs-jquery-parents/2 has an empty `<tbody>`.

Somehow, no tests were inserted into the database for this page:

```
mysql> select * from tests where pageID = 1303938;
Empty set (0.00 sec)
```

Any ideas how this happened?

**Comment by bd82** [comment] 2016-10-19 20:29
I think I can reproduce this.

* I made a test case: https://jsperf.com/javascript-parsing-libraries-benchmark/1

* I tried editing it to fix a bad URL. https://jsperf.com/javascript-parsing-libraries-benchmark/1/edit

* I get **Not all tests inserted** after saving the test.

* If I open the new revision e.g: https://jsperf.com/javascript-parsing-libraries-benchmark/2 
   There will be no test cases present in it.

**Comment by gionkunz** [comment] 2016-10-27 20:18
This seems to happen for me for every created scenario (just tried to edit one I've just created)

**Comment by talee** [comment] 2016-10-27 20:20
Reprod via editing a new one just now.

**Comment by japzi** [comment] 2016-10-31 14:45
Happens to me as well, I can't edit a test without getting "Not all tests inserted".

**Comment by zwacky** [comment] 2016-11-03 10:15
reproducable on my part as well. trying to edit a test with 2 cases and getting "Not all tests inserted".

The POST request (https://jsperf.com/my-test-name/1/edit) returns 400.

**Comment by SeanJM** [comment] 2016-11-04 20:36
reproducible for me too https://jsperf.com/startswith-or-regex2-or-slice-or-substr-or-indexof/1/edit

**Comment by Jameskmonger** [comment] 2016-11-08 14:54
Reproducible for me too at https://jsperf.com/array-destroy/224 (edited at https://jsperf.com/array-destroy/224/edit)

**Comment by MatthewRalston** [comment] 2016-11-08 20:04
I am getting the same issue. First POST is "not all tests inserted" followed by a locking up of the form with "Please review the required fields and save again", where the field is filled out in the HTML.

**Comment by dinazil** [comment] 2016-11-20 09:07
Same here: can't edit https://jsperf.com/parentorselector

**Comment by kalvindukes** [comment] 2016-11-30 11:26
Can't even add any tests to edits due to missing buttons and the reproducible errors on this issue

**Comment by maxbeatty** [comment] 2016-12-24 05:23
If you're in a position to sponsor jsPerf, please see #291

**Comment by jake-macadamian** [comment] 2017-01-03 15:59
Reproduced: https://jsperf.com/jquery-each-vs-underscore-each-vs-for-loops/104

**Comment by manico** [comment] 2017-01-05 08:20
Same here: https://jsperf.com/scd-float-rounding/1/edit

**Comment by mathiasbynens** [comment] 2017-01-12 11:02
Thanks to @LeZuse and @maxbeatty #311 was just merged and deployed. Does that help?

**Comment by m93a** [comment] 2017-01-12 21:00
Still having problems with http://jsperf.com/rounding-a-number

**Comment by maxbeatty** [comment] 2017-01-12 21:25
Will you please provide more detail? It really helps shorten the time needed to fix

**Comment by dcodeIO** [comment] 2017-01-13 04:19
Also still having an issue:

* Logged in via GitHub
* Redirected to GitHub to authorize
* Redirected to jsPerf, need to click the GitHub button again
* Not sure if I'm logged in
* Created a new test (no name, email, website, just prep code, setup, 2 named snippets, non-published to keep fiddling around) and saved
* [Revision 1](https://jsperf.com/protobuf-js-bench/1) is ok
* Edited it, added 4 new code snippets (didn't edit anything else), saved
* Redirected to recaptcha (is this from cloudflare?) to approve that I'm a human
* Redirected to jsPerf, showing "Not all tests inserted"
* Opening [Revision 2](https://jsperf.com/protobuf-js-bench/2) manually shows only the new 4 code snippets
* From there on nothing seems to work anymore (edited different things, not sure what exactly):
  * [Revision 3](https://jsperf.com/protobuf-js-bench/3) has just one snippet
  * [Revision 4](https://jsperf.com/protobuf-js-bench/4) has none

**Comment by dcodeIO** [comment] 2017-01-13 17:29
The issue apparently is that, when [updating tests](https://github.com/jsperf/jsperf.com/blob/master/server/repositories/tests.js#L39), the SQL query contains a `WHERE pageID=NEWID` clause, where `NEWID` is given as the page id of the new revision, which updates nothing, because the stored pageID is that of the old revision.

**Comment by dcodeIO** [comment] 2017-01-13 17:46
Do you know if it is actually possible to UPDATE an existing test, without creating a new revision?

**Comment by mathiasbynens** [comment] 2017-01-13 18:04
> Do you know if it is actually possible to UPDATE an existing test, without creating a new revision?

In jsPerf v1, this was possible until your session expired.

**Comment by dcodeIO** [comment] 2017-01-13 18:20
There it is!

**Comment by samiraguiar** [comment] 2017-01-18 12:05
This is still happening to me when editing this test: https://jsperf.com/stringreplaceall-544/1/edit

**Comment by stevenvachon** [comment] 2017-01-20 22:43
My revisions are empty: https://jsperf.com/substr-split-vs-split-shift/

**Comment by ericblade** [comment] 2017-01-22 21:19
fwiw, i've never been able to edit on jsperf, and i've tried many times over the last couple of years.  always same error.

**Comment by xZero707** [comment] 2017-01-27 20:10
Guess what brought me here? 
I just tried to edit, again after a looong time, and same as then, same error. There is absolutely nothing to be filled out, still it doesn't work.

**Comment by nuxy** [comment] 2017-01-28 22:44
Same issue here. Old project that needed an update.

**Reproducing**
- Access the URL (https://jsperf.com/datatype-fu/edit)
- Edit the Preparation Code
- Save Test Case

.. _I am not a robot_

**Result**
- Error returned "Not all tests inserted"
- Revision created.

**Failed attempts that should be removed**
https://jsperf.com/datatype-fu/2
https://jsperf.com/datatype-fu/3
https://jsperf.com/datatype-fu/4
https://jsperf.com/datatype-fu/5

**Comment by maxbeatty** [comment] 2017-01-29 03:16
I deployed `master` to https://jsperf-max.now.sh/ with a new database (my next to last guess on what's causing this). if you could, please see if tests are post correct in this environment and add a reaction to this comment of 👍 if it works or 👎 if it doesn't

some quick notes on this environment:

1. no cloudflare
2. no previous tests (new, empty database instance)

if all goes well, I'll figure out how to get the old data into the new database

**Comment by stevenvachon** [comment] 2017-01-29 15:14
Still producing empty revisions here too.

**Comment by TC72** [comment] 2017-01-30 00:07
Is there any chance the captcha is causing form data to be lost when it's submitted?

**Comment by stevenvachon** [comment] 2017-01-30 05:58
@TC72 I never once saw a captcha.

**Comment by TC72** [comment] 2017-01-30 08:22
@stevenvachon thanks for confirming, I'd seen it mentioned by someone else but if you don't see it then I was barking up the wrong tree.

**Comment by rjamesnw** [comment] 2017-02-02 16:12
Having the same issue here: https://jsperf.com/iterative-array-flatten/3
Now there's a bunch of bogus posts because of the glitch. I filled out ALL fields, and nothing I do will work (using Chrome). Haven't tried another browser yet.

**Comment by Gimmo** [comment] 2017-02-04 03:35
"Not all tests inserted"
https://jsperf.com/fastest-array-loops-in-javascript/577  **577 !!!**

**Comment by stevenvachon** [comment] 2017-02-04 18:47
jsperf.com has been broken for years, so this isn't really anything new. Is there a better alternative?

**Comment by rjamesnw** [comment] 2017-02-04 20:06
Where really needs to be a way to delete a revision by the OP, otherwise it gets cluttered fast with erroneous posts. Perhaps put a time limit on it if necessary, so after say a month it cannot be deleted, or perhaps if another revision exists after, it can't be deleted, etc.

**Comment by jonathanarbely** [comment] 2017-02-06 17:58
Doesn't work for me too.
https://jsperf.com/caching-jquery-selectors

**Comment by sylido** [comment] 2017-02-06 19:35
Doesn't work for https://jsperf.com/jquery-each-vs-each-vs-for-loop/ as well :(

**Comment by maxbeatty** [comment] 2017-02-06 19:39
> We have enough comments on this being reproducible. Submitting a pull request with a fix is the best contribution.

**Comment by mindplay-dk** [comment] 2017-10-05 08:41
Doesn't work for me either, trying to fork [this](https://jsperf.com/math-clamp/9/edit) one.

**Comment by GCDeveloper** [comment] 2017-10-10 20:38
still not fixed?
use
jsbench.me
jsben.ch
jsperf.co
measurethat.net

**Comment by arthurlacoste** [comment] 2017-10-31 15:18
Still happening for me.

**Comment by manucorporat** [comment] 2017-11-13 13:28
Still a problem! https://jsperf.com/reusable-args-vs-local-vars/3

**Comment by grave-dancer** [comment] 2017-11-16 23:00
best website ever... this problem has still not been fixed as of november 2017 and it seems the staff blame cloudfare

**Comment by jangajack** [comment] 2017-11-29 00:18
This is still an issue. My edits to a test suite have totally screwed up the history.

https://jsperf.com/document-fragment-vs-innerhtml-vs-looped-appendchild/

Edits 70-73 are garbage. Is this under active investigation?

**Comment by alphanull** [comment] 2017-11-29 15:22
+1 - also a problem for me. Had to manually clear the DB and reenter everything ... (running local installation)

**Comment by alphanull** [comment] 2017-11-29 15:36
Basically, jsperf is more or less unusable because of this bug, it JUST happened again, forcing me to restart everything and clear the DB. I also made other observations that _might_ contribute:

- I cannot see "my Tests" anymore after logging in the next day
- The test I have created does NOT show up in "latest", only with "popular"
- Despite the failed attempt to edit my test, a new "revision" (or at least another DB entry) is created nonetheless, but not marked as a new revision. I.e. the two entries I see under "latest" are pointing to the same URL.
- But then, all tests in the tests Table still point to the first entry. maybe thats the source of the error?
- Browserscope ID is different with the new entry, maybe it has something to do with that?
- After a while (8 hours according to docs), jsperf forces a new revision. I think this limit shouldn't be there or at least configurable, esp. on local installations

And it should be possible to have only a local login, or none at all for a local installation, but think this is another topic.

**Please**, fix this bug, this is quite serious and makes working with jsperf almost impossible right now (at least for me)!

**Comment by AlexGalays** [comment] 2017-12-24 12:52
This issue is quite a blocker haha, can't edit anything.

@GCDeveloper listed some sites that work and are actually maintained (or less buggy from the get go):

jsbench.me
jsben.ch
measurethat.net

**Closed** 2018-03-11 14:41 UTC
Labels: bug, confirmed
