### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by thdoan** [jsperf/jsperf.com#53] opened 2015-10-25 17:21 UTC
I'm seeing this error on the page below:

```
Uncaught TypeError: Cannot read property 'name' of undefined.

message: Uncaught TypeError: Cannot read property 'name' of undefined
fileName: http://jsperf.com/benchmark-47.js
lineNumber: 21
```

Source: http://jsperf.com/ways-to-strip-last-comma

**Comment by mrcoles** [comment] 2015-11-12 15:06
this is a duplicate of https://github.com/jsperf/jsperf.com/issues/45

**Comment by mathiasbynens** [comment] 2016-01-27 18:45
Closing in favor of #64.

**Closed by mathiasbynens** 2016-01-27 18:45 UTC
