### ISSUE TITLE
Receiving error on simple script

### ISSUE THREAD

**Issue by steebchen** [jsperf/jsperf.com#45] opened 2015-10-03 11:08 UTC
I [created a test](http://jsperf.com/foreach-in-object-vs-selecting-object-from-index) on jsperf, but it shows an error, but not in my script:

    Uncaught TypeError: Cannot read property 'name' of undefined.
      message: Uncaught TypeError: Cannot read property 'name' of undefined
      fileName: http://jsperf.com/benchmark-47.js
      lineNumber: 21

What is wrong with my test?

**Comment by gwicksted** [comment] 2015-10-05 12:48
I had this too recently when testing NodeListJS [ticket 4](https://github.com/eorroe/NodeList.js/issues/4).  eorroe had this to say:

> Seems to be a jsperf problem
> when you debug it, its doing:
```javascript
(R = T.createElement(U)).name = S;
```
`T.createElement(U)` returns a div and then it trys to get the property `name` which is `undefiend`

**Comment by maxbeatty** [comment] 2015-10-05 18:04
Looks like you may possibly be having the same problem as #44. Sorry I don't have more info at the moment.

**Comment by tolgaek** [comment] 2015-10-13 14:27
Doesn't seem to effect the tests? I'm getting the same error on Chrome

**Comment by lpsBetty** [comment] 2015-11-03 20:02
What is this strange jsperf.com bug? It does not happen on every test case... but at mine: http://jsperf.com/replace-xpath-vs-text

**Comment by mrcoles** [comment] 2015-11-12 15:00
+1

**Comment by tanepiper** [comment] 2015-11-16 13:39
JSPerf seems to want to run a piece of Java code!  In the benchmark-47.js file, at line 1978 there is a ui.js reference, and in here looks like it's trying to load nano.jar.

By default my Chrome does not run Java code.

Looking at it, it looks like a shim for Opera Mini, but it's breaking Chrome.  In Firefox I noticed that it asked me to also run this Java, and I got a very similar error (although it has P[0] as the reference).

**Comment by fracalo** [comment] 2015-11-29 12:33
same here on chrome  ||  http://jsperf.com/array-with-keyprop-vs-object

**Comment by mcshaman** [comment] 2015-12-03 09:50
+1

**Comment by pjasiun** [comment] 2015-12-14 14:08
+1

**Comment by deepak-jacob** [comment] 2015-12-22 11:51
+1  http://jsperf.com/regex-test-noncapturepara

**Comment by yukulele** [comment] 2015-12-22 13:07
+1

**Comment by bd82** [comment] 2015-12-24 22:29
+1

**Comment by kof** [comment] 2016-01-21 10:44
Yep, also got this issue http://jsperf.com/css-selectors-amount-influences-dom-performance/3

**Comment by kof** [comment] 2016-01-21 11:07
Safari gave me a better error description

```
TypeError: undefined is not an object (evaluating 'P("iframe",W.container)[0].name').

message: TypeError: undefined is not an object (evaluating 'P("iframe",W.container)[0].name')
fileName: http://jsperf.com/benchmark-47.js
lineNumber: 21
```

**Comment by hasMichaels** [comment] 2016-01-22 23:59
+1 Same as @kof

**Comment by steebchen** [comment] 2016-01-25 14:59
Can you please stop giving "+1" comments without adding value (like kof, he gave an error description when using Safari). I like to get news about this topic when a new comment is added, but not simple "+1" comments.

**Comment by kof** [comment] 2016-01-25 15:04
@steebchen sometimes its important for maintainers to see if the issue is actually often a problem and how of people are affected by it. This can change priority. Alternatively some plugins like zenhub needs to be used.

**Comment by alfonsomartinde** [comment] 2016-01-27 12:07
Same here http://jsperf.com/angular-element-find-vs-document-getelementbyid/6
And Firefox throwing:

    TypeError: P(...)[0] is undefined.

        message: TypeError: P(...)[0] is undefined
        fileName: http://jsperf.com/benchmark-47.js
        lineNumber: 21

**Comment by mathiasbynens** [comment] 2016-01-27 18:45
Closing in favor of #64.

**Closed by mathiasbynens** 2016-01-27 18:45 UTC
